backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "imgs/uploads"
site_url: https://petradios.eu
collections:
  - name: "Projects"
    folder: "_posts/projects"
    create: true
    extension: markdown
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    preview_path: "blog/{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "projects"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}